name: zooq
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts_arabic: ^1.1.7
  carousel_slider: ^1.3.0
  carousel_pro: ^0.0.13
  share: ^0.6.2+1
  image_picker: ^0.6.1+4
  smooth_star_rating: ^1.0.3
  google_maps_flutter: ^0.5.20+6
  location: ^2.3.5
  auto_size_text: ^2.1.0
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.10+2
  firebase_auth: ^0.15.0+1
  provider: ^3.1.0
  device_preview: ^0.2.6







  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo-zooq.png"
  image_path_android: "images/logo-zooq.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/
  fonts:
     - family: cairo
       fonts:
         - asset: fonts/Cairo-Black.ttf
         - asset: fonts/Cairo-Bold.ttf
         - asset: fonts/Cairo-BoldItalic.ttf
         - asset: fonts/Cairo-ExtraLight.ttf
         - asset: fonts/Cairo-ExtraLightItalic.ttf
         - asset: fonts/Cairo-Italic.ttf
         - asset: fonts/Cairo-Light.ttf
         - asset: fonts/Cairo-LightItalic.ttf
         - asset: fonts/Cairo-Regular.ttf
         - asset: fonts/Cairo-SemiBold.ttf
         - asset: fonts/Cairo-SemiBoldItalic.ttf
           style: italic